import type { Contact, Product } from '@/types'
import { generateId } from '@/utils/id'
import { db, isSeeded, markSeeded } from './storage'

const now = new Date().toISOString()

function product(
  partial: Omit<Product, 'id' | 'createdAt' | 'updatedAt'>,
): Product {
  return {
    ...partial,
    id: generateId(),
    createdAt: now,
    updatedAt: now,
  }
}

const seedProducts: Product[] = [
  product({
    sku: 'IPH15-128-BLK',
    brand: 'Apple',
    model: 'iPhone 15',
    variant: 'Negro 128GB',
    category: 'celular',
    condition: 'nuevo',
    price: 18999,
    cost: 15200,
    stock: 8,
    minStock: 3,
    specs: { storage: '128GB', color: 'Negro', screen: '6.1"' },
  }),
  product({
    sku: 'IPH15P-256-NAT',
    brand: 'Apple',
    model: 'iPhone 15 Pro',
    variant: 'Titanio Natural 256GB',
    category: 'celular',
    condition: 'nuevo',
    price: 26999,
    cost: 22100,
    stock: 4,
    minStock: 2,
    specs: { storage: '256GB', color: 'Titanio Natural', screen: '6.1"' },
  }),
  product({
    sku: 'SGS24-256-GRY',
    brand: 'Samsung',
    model: 'Galaxy S24',
    variant: 'Gris 256GB',
    category: 'celular',
    condition: 'nuevo',
    price: 17999,
    cost: 14500,
    stock: 6,
    minStock: 3,
    specs: { storage: '256GB', color: 'Gris', screen: '6.2"' },
  }),
  product({
    sku: 'SGZA55-128-BLU',
    brand: 'Samsung',
    model: 'Galaxy A55',
    variant: 'Azul 128GB',
    category: 'celular',
    condition: 'nuevo',
    price: 8999,
    cost: 6800,
    stock: 12,
    minStock: 5,
    specs: { storage: '128GB', color: 'Azul' },
  }),
  product({
    sku: 'XM14T-256-BLK',
    brand: 'Xiaomi',
    model: '14T',
    variant: 'Negro 256GB',
    category: 'celular',
    condition: 'nuevo',
    price: 10999,
    cost: 8200,
    stock: 2,
    minStock: 4,
    specs: { storage: '256GB', color: 'Negro' },
  }),
  product({
    sku: 'MOTO-G84-256',
    brand: 'Motorola',
    model: 'Moto G84',
    variant: 'Viva Magenta 256GB',
    category: 'celular',
    condition: 'nuevo',
    price: 6499,
    cost: 4800,
    stock: 7,
    minStock: 3,
  }),
  product({
    sku: 'IPH13-128-BLK-2D',
    brand: 'Apple',
    model: 'iPhone 13',
    variant: 'Negro 128GB',
    category: 'celular',
    condition: 'segunda_mano',
    price: 9999,
    cost: 7500,
    stock: 3,
    minStock: 1,
    specs: { storage: '128GB', color: 'Negro' },
  }),
  product({
    sku: 'SGS22-128-GRN-2D',
    brand: 'Samsung',
    model: 'Galaxy S22',
    variant: 'Verde 128GB',
    category: 'celular',
    condition: 'segunda_mano',
    price: 7499,
    cost: 5500,
    stock: 2,
    minStock: 1,
    specs: { storage: '128GB', color: 'Verde' },
  }),
  product({
    sku: 'XM-REDMI-N13-2D',
    brand: 'Xiaomi',
    model: 'Redmi Note 13',
    variant: 'Negro 128GB',
    category: 'celular',
    condition: 'segunda_mano',
    price: 3999,
    cost: 2800,
    stock: 5,
    minStock: 2,
  }),
  product({
    sku: 'CASE-IPH15-SIL',
    brand: 'Spigen',
    model: 'Funda iPhone 15',
    variant: 'Silicona Transparente',
    category: 'accesorio',
    price: 399,
    cost: 180,
    stock: 25,
    minStock: 10,
  }),
  product({
    sku: 'CASE-S24-LEA',
    brand: 'Spigen',
    model: 'Funda Galaxy S24',
    variant: 'Cuero Negro',
    category: 'accesorio',
    price: 549,
    cost: 260,
    stock: 18,
    minStock: 8,
  }),
  product({
    sku: 'CABLE-USB-C-2M',
    brand: 'Anker',
    model: 'Cable USB-C',
    variant: '2 metros 100W',
    category: 'accesorio',
    price: 299,
    cost: 120,
    stock: 40,
    minStock: 15,
  }),
  product({
    sku: 'CHARGER-20W',
    brand: 'Anker',
    model: 'Cargador 20W',
    variant: 'USB-C PD',
    category: 'accesorio',
    price: 449,
    cost: 200,
    stock: 3,
    minStock: 10,
  }),
  product({
    sku: 'EARBUDS-PRO',
    brand: 'Samsung',
    model: 'Galaxy Buds2 Pro',
    variant: 'Negro',
    category: 'accesorio',
    price: 3499,
    cost: 2400,
    stock: 9,
    minStock: 4,
  }),
  product({
    sku: 'SCR-IPH15-TG',
    brand: 'Belkin',
    model: 'Protector iPhone 15',
    variant: 'Vidrio Templado',
    category: 'accesorio',
    price: 349,
    cost: 90,
    stock: 30,
    minStock: 12,
  }),
  product({
    sku: 'PWRBANK-10K',
    brand: 'Xiaomi',
    model: 'Power Bank 10000mAh',
    variant: 'Negro',
    category: 'accesorio',
    price: 599,
    cost: 280,
    stock: 15,
    minStock: 6,
  }),
  product({
    sku: 'HOLDER-MAG',
    brand: 'Baseus',
    model: 'Soporte Magnético',
    variant: 'Para auto',
    category: 'accesorio',
    price: 279,
    cost: 110,
    stock: 22,
    minStock: 8,
  }),
  product({
    sku: 'SIM-PREPAGO',
    brand: 'Telcel',
    model: 'SIM Prepago',
    variant: 'Chip estándar',
    category: 'otro',
    price: 49,
    cost: 20,
    stock: 50,
    minStock: 20,
  }),
  product({
    sku: 'IPAD-10-64',
    brand: 'Apple',
    model: 'iPad 10ª gen',
    variant: '64GB WiFi',
    category: 'tablet',
    price: 8999,
    cost: 7200,
    stock: 4,
    minStock: 2,
  }),
  product({
    sku: 'AW-S9-41',
    brand: 'Apple',
    model: 'Watch Series 9',
    variant: '41mm GPS',
    category: 'smartwatch',
    price: 7499,
    cost: 5900,
    stock: 3,
    minStock: 2,
  }),
  product({
    sku: 'MBA-M2-256',
    brand: 'Apple',
    model: 'MacBook Air M2',
    variant: '256GB 13"',
    category: 'computadora',
    price: 22999,
    cost: 18500,
    stock: 2,
    minStock: 1,
  }),
]

const seedSuppliers: Contact[] = [
  {
    id: generateId(),
    name: 'Distribuidora TecnoMayoreo',
    type: 'supplier',
    phone: '555-8080',
    notes: 'Mayorista de equipos nuevos Apple y Samsung',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: generateId(),
    name: 'Importaciones GadgetPro',
    type: 'supplier',
    phone: '555-9090',
    notes: 'Accesorios y equipos de segunda mano',
    createdAt: now,
    updatedAt: now,
  },
]

export async function seedDatabaseIfNeeded(): Promise<void> {
  if (await isSeeded()) return

  await db.transaction('rw', db.products, db.contacts, async () => {
    await db.products.bulkAdd(seedProducts)
    await db.contacts.bulkAdd(seedSuppliers)
  })

  await markSeeded()
}